Repository tact-lang/tact, pull requests merged in 2023-11, with the labels that each got.

#81 Allow only type identifiers for structs/messages
  src/grammar/__snapshots__/grammar.spec.ts.snap
  src/grammar/grammar.ohm
  src/grammar/grammar.ohm-bundle.js
  src/grammar/test-failed/case-10.tact
Labels: syntax

#83 Only type identifiers for messages with overwritten OP
  src/grammar/__snapshots__/grammar.spec.ts.snap
  src/grammar/grammar.ohm
  src/grammar/grammar.ohm-bundle.js
  src/grammar/test-failed/case-11.tact
Labels: syntax

#86 fix[test]: update `to` address in wallet snapshot
  examples/__snapshots__/wallet.spec.ts.snap
Labels: bug, testing

#96 add ubuntu & windows & macos CI
  .github/workflows/node.js.yml
  package.json
  scripts/pack.ts
  src/pipeline/build.ts
  src/utils/filePath.ts
  yarn.lock
Labels: enhancement, infrastructure

#104 doc: update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
