Repository tact-lang/tact, pull requests merged in 2024-03, with the labels that each got.

#175 Implement address dumping
  CHANGELOG.md
  src/abi/global.ts
  src/generator/Writer.ts
  src/generator/writers/__snapshots__/writeSerialization.spec.ts.snap
  src/generator/writers/writeStdlib.ts
  src/test/feature-debug.spec.ts
  src/test/features/debug.tact
Labels: language feature

#166 Implement `log2` and `log` functions in math.tact
  CHANGELOG.md
  src/generator/writers/__snapshots__/writeSerialization.spec.ts.snap
  src/generator/writers/writeStdlib.ts
  src/imports/stdlib.ts
  src/test/feature-math.spec.ts
  src/test/features/math.tact
  stdlib/std/math.tact
Labels: enhancement, stdlib

#167 implicit init function if not present
  CHANGELOG.md
  src/test/__snapshots__/feature-implicit-init.spec.ts.snap
  src/test/feature-implicit-init.spec.ts
  src/test/features/implicit-init-2.tact
  src/test/features/implicit-init.tact
  src/test/features/output/implicit-init_MyContract.abi
  src/test/features/output/implicit-init_MyContract.code.boc
  src/test/features/output/implicit-init_MyContract.code.fc
  src/test/features/output/implicit-init_MyContract.code.fif
  src/test/features/output/implicit-init_MyContract.code.rev.fif
  src/test/features/output/implicit-init_MyContract.headers.fc
  src/test/features/output/implicit-init_MyContract.md
  src/test/features/output/implicit-init_MyContract.pkg
  src/test/features/output/implicit-init_MyContract.stdlib.fc
  src/test/features/output/implicit-init_MyContract.storage.fc
  src/test/features/output/implicit-init_MyContract.ts
  src/test/test-tact.config.json
  src/types/resolveDescriptors.ts
  tact.config.json
Labels: language feature

#184 Add the mock context constructor needed for tests
  src/grammar/store.ts
Labels: api

#173 Add constants for reserve modes
  examples/payouts.tact
  examples/rugpull.tact
  src/imports/stdlib.ts
  stdlib/std/base.tact
  stdlib/std/reserve.tact
Labels: enhancement, stdlib

#188 doc: update CHANGELOG with new reserve mode constants
  CHANGELOG.md
Labels: documentation

#202 chore: add a pull request template
  .github/workflows/pull_request_template.md
Labels: infrastructure

#194 JSON Schema for Tact configuration
  .github/workflows/tact.yml
  CHANGELOG.md
  grammar/configSchema.json
  package.json
  src/config/parseConfig.ts
  src/test/test-tact.config.json
  tact.config.json
  yarn.lock
Labels: ux, ci, tooling
