Repository tact-lang/tact, pull requests merged in 2024-02, with the labels that each got.

#97 Add conditional expressions
  src/generator/writers/writeExpression.ts
  src/grammar/__snapshots__/grammar.spec.ts.snap
  src/grammar/ast.ts
  src/grammar/clone.ts
  src/grammar/grammar.ohm
  src/grammar/grammar.ohm-bundle.d.ts
  src/grammar/grammar.ohm-bundle.js
  src/grammar/grammar.ts
  src/grammar/test/case-29.tact
  src/grammar/test/case-30.tact
  src/grammar/test/case-31.tact
  src/grammar/test/case-32.tact
  src/test/feature-ternary.spec.ts
  src/test/features/output/ternary_TernaryTester.abi
  src/test/features/output/ternary_TernaryTester.code.boc
  src/test/features/output/ternary_TernaryTester.code.fc
  src/test/features/output/ternary_TernaryTester.code.fif
  src/test/features/output/ternary_TernaryTester.code.rev.fif
  src/test/features/output/ternary_TernaryTester.headers.fc
  src/test/features/output/ternary_TernaryTester.md
  src/test/features/output/ternary_TernaryTester.pkg
  src/test/features/output/ternary_TernaryTester.stdlib.fc
  src/test/features/output/ternary_TernaryTester.storage.fc
  src/test/features/output/ternary_TernaryTester.ts
  src/test/features/ternary.tact
  src/types/__snapshots__/resolveStatements.spec.ts.snap
  src/types/resolveExpression.ts
  src/types/stmts-failed/case-26.tact
  src/types/stmts-failed/case-27.tact
  src/types/stmts-failed/case-28.tact
  src/types/stmts-failed/case-29.tact
  tact.config.json
Labels: language feature

#134 chore: update changelog with ternary operator
  CHANGELOG.md
Labels: documentation

#137 feat[cli]: --version flag
  .github/workflows/node.js.yml
  bin/tact
Labels: enhancement, cli

#111 Refactor CI workflow and add tact-template testing
  .github/workflows/node.js.yml
  .github/workflows/tact.yml
Labels: ci

#122 add `SendBounceIfActionFail` flag for sendmode from TVM update
  CHANGELOG.md
  src/imports/stdlib.ts
  stdlib/std/send.tact
Labels: enhancement

#105 Slices and Strings comparisons
  CHANGELOG.md
  src/generator/writers/__snapshots__/writeSerialization.spec.ts.snap
  src/generator/writers/writeExpression.ts
  src/generator/writers/writeStdlib.ts
  src/test/feature-math.spec.ts
  src/test/features/math.tact
  src/types/resolveExpression.ts
Labels: language feature

#139 chore[changelog]: mention tact-template in CI
  CHANGELOG.md
Labels: documentation

#145 chore[changelog]: `==` and `!=` typechecker bug fixed
  CHANGELOG.md
Labels: documentation

#152 Add Blueprint to CI
  .github/workflows/tact.yml
  CHANGELOG.md
Labels: ci
