Repository tact-lang/tact, pull requests merged in 2024-04, with the labels that each got.

#208 Fix checks for key existance in objects
  CHANGELOG.md
  src/abi/global.ts
  src/abi/map.ts
  src/abi/struct.ts
  src/generator/writers/writeExpression.ts
  src/types/__snapshots__/resolveStatements.spec.ts.snap
  src/types/resolveDescriptors.ts
  src/types/resolveExpression.ts
  src/types/resolveStatements.ts
  src/types/stmts-failed/case-30.tact
  src/types/stmts/case-10.tact
  src/types/stmts/case-11.tact
  src/types/stmts/case-12.tact
Labels: errors

#192 Implement string escaping and fix bug with error messages
  CHANGELOG.md
  src/bindings/writeTypescript.ts
  src/generator/writers/writeExpression.ts
  src/grammar/grammar.ohm
  src/grammar/grammar.ohm-bundle.d.ts
  src/grammar/grammar.ohm-bundle.js
  src/test/__snapshots__/bugs.spec.ts.snap
  src/test/bugs.spec.ts
  src/test/bugs/bugs.tact
  src/test/bugs/issue53.tact
  src/test/feature-strings.spec.ts
  src/test/features/strings.tact
Labels: syntax, language feature

#224 Add `toString` for `Address` type
  CHANGELOG.md
  src/imports/stdlib.ts
  src/test/feature-strings.spec.ts
  src/test/features/strings.tact
  stdlib/std/text.tact
Labels: stdlib

#179 Support for trailing comma
  CHANGELOG.md
  src/grammar/__snapshots__/grammar.spec.ts.snap
  src/grammar/grammar.ohm
  src/grammar/grammar.ohm-bundle.d.ts
  src/grammar/grammar.ohm-bundle.js
  src/grammar/grammar.ts
  src/grammar/test-failed/case-19.tact
  src/grammar/test-failed/case-20.tact
  src/grammar/test-failed/case-21.tact
  src/grammar/test-failed/case-22.tact
  src/grammar/test-failed/case-23.tact
  src/grammar/test-failed/case-24.tact
  src/grammar/test-failed/case-25.tact
  src/grammar/test-failed/case-26.tact
  src/grammar/test/case-17.tact
  src/grammar/test/case-25.tact
Labels: syntax, language feature

#237 Constant evaluation of `newAddress`
  CHANGELOG.md
  src/test/feature-constants.spec.ts
  src/test/features/constants.tact
  src/types/resolveConstantValue.ts
Labels: scope: const-eval

#212 Implement try-catch statements
  CHANGELOG.md
  src/generator/writers/writeFunction.ts
  src/grammar/ast.ts
  src/grammar/clone.ts
  src/grammar/grammar.ohm
  src/grammar/grammar.ts
  src/test/__snapshots__/feature-try-catch.spec.ts.snap
  src/test/feature-try-catch.spec.ts
  src/test/features/try-catch.tact
  src/types/__snapshots__/resolveStatements.spec.ts.snap
  src/types/resolveStatements.ts
  src/types/stmts-failed/case-32.tact
  src/types/stmts-failed/case-33.tact
  src/types/stmts-failed/case-34.tact
  src/types/stmts-failed/case-35.tact
  tact.config.json
Labels: language feature
