Repository tact-lang/tact, pull requests merged in 2025-01, with the labels that each got.

#1344 Tests for extension functions
  src/types/__snapshots__/resolveDescriptors.spec.ts.snap
  src/types/test-failed/extend-fun-cannot-be-defined-within-contract.tact
  src/types/test-failed/extend-fun-cannot-be-defined-within-trait.tact
  src/types/test-failed/extend-fun-missing-type.tact
  src/types/test-failed/extend-fun-must-have-at-least-one-parameter.tact
Labels: testing

#1296 doc(stdlib): doc comments for `BaseTrait`
  CHANGELOG.md
  src/stdlib/stdlib.ts
  src/stdlib/stdlib/std/base.tact
  src/stdlib/stdlib/std/primitives.tact
  src/stdlib/stdlib/stdlib.tact
Labels: stdlib

#1417 refactor(deps): remove `rimraf`
  package.json
  src/vfs/createNodeFileSystem.spec.ts
  yarn.lock
Labels: scope: project

#1393 test: add tests for asm instructions without whitespace
  src/grammar/next/__snapshots__/grammar.spec.ts.snap
  src/grammar/next/grammar.spec.ts
  src/grammar/next/test/asm-instruction-no-whitespace-1.tact
  src/grammar/next/test/asm-instruction-no-whitespace-2.tact
  src/grammar/next/test/asm-instruction-no-whitespace-3.tact
Labels: kind: testing, scope: parser

#1502 fix: lychee fails on windows
  .github/workflows/tact-docs-test.yml
  .github/workflows/tact.yml
Labels: scope: ci

#1570 merged random generation functions for tests into one file
  examples/wallet.spec.ts
  src/test/e2e-emulated/map1.spec.ts
  src/test/e2e-emulated/map2.spec.ts
  src/test/e2e-emulated/math.spec.ts
  src/test/e2e-emulated/optionals.spec.ts
  src/test/utils/random-utils.ts
  src/test/utils/randomAddress.ts
  src/test/utils/testKey.ts
Labels: kind: refactoring, kind: testing

#1563 put the linter launch in a separate job
  .github/workflows/linter.yml
  .github/workflows/tact.yml
Labels: scope: ci
